spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database: POSTGRESQL
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipesite
    username: ${psql.user}
    password: ${psql.password}